= Childish Gambino (This is America) - Some Thoughts

* Video: https://www.youtube.com/watch?v=VYOjWnS4cMY
* Lyrics: https://genius.com/14498761

Overall Themes:

* Racism
* Gun Violence (against black people)
* Police brutality
* Materialism in the modern HipHop culture
* Willful ignorace towards social issues
* Ignorance fueled by media distractions
* Stampede panic in the society
** Everybody tries to flee from what they are afraid of
** In the end it looks like everybody is coming for you
** Ultimately everybody is afraid and (mentally/ideologically) runs from the society that is just as afraid (of the same things) as they are

== Observations

* Focus on the dance moves and appearances
* Incredible how desensitized people are against people getting shot in the video
* A lot of the reaction videos show a disbelief towards the first shooting,
* Also a lot of videos show a disbelief by laughter or a general confusion about the first shooting.
* Generally most reaction videos depict a negative emotional reaction to the shooting of the choir (at 1:55/link:https://youtu.be/VYOjWnS4cMY?t=115[Choir shooting]) preceded by a general amusement about Donald's dance moves (and thus * being distracted from the previous violence)
* After the first person got shot I was completely distraught and couldn't get into the dancing or any other aspect of the video.
* When the choir was shot I immediately made the connection towards the Charleston shooting and how no place was safe from this kind of violence.
* I am astonished, amazed and downright disgusted by the reaction of black americans to the violence in this video. I have to assume it was their first exposure to this video in particular.
* My point here being: "If you have an entire generation of people so used to violence that it does not make an impact anymore"; how are you going to change a country?
* I think this is one of the ideas that Donald Glover and Hiro Murai were aiming at during the production of this video.

== Reactions Watched

https://www.youtube.com/watch?v=zEKr4LSBA7k
https://www.youtube.com/watch?v=qgvgMmgTjDw
https://www.youtube.com/watch?v=4rurVL9_sss
https://www.youtube.com/watch?v=ZVhg3FJrSDE
https://www.youtube.com/watch?v=NCKgflcauH0
https://www.youtube.com/watch?v=JpHRBh_oZ8k
https://www.youtube.com/watch?v=eCSJiQuFRMo
https://www.youtube.com/watch?v=9tfEn6srem0
https://www.youtube.com/watch?v=w2V5kHKxSBI
https://www.youtube.com/watch?v=_q16h4rBLMo
https://www.youtube.com/watch?v=lopHzDNfIWI
https://www.youtube.com/watch?v=m22TKCt2Kt0
https://www.youtube.com/watch?v=JGFiCTLLEFc
https://www.youtube.com/watch?v=3Kc_GZxtn6E
https://www.youtube.com/watch?v=YgCRooFZYLA
https://www.youtube.com/watch?v=XLduOks4Gqc
