== Dialog Bullshit

Wenn du sagst "Bringt ihn raus" muss das irgendwas heissen
ansonsten zeig die Leute die entscheiden (muessen) was die mit dem Typen machen.

Du kannst nicht sagen

-Der wurrde von unseren Feinden gefoltert und hat unser Koksversteck verraten-
"Bringt ihn raus"

Und dann

-Das ist der Chef unserer rivalisierenden Gang, der hat mir gerade gesagt dass er weiss dass unser Krieg auf einer vollkommen falschen Annahme basiert, haengt den in der Garage auf
"Bringt ihn raus"

What the fuck. Das sind dermaßen unterschiedliche Dinge. Warum passiert das?

== Regie Episode

Warum offenbart sich Vince den Hamady's nach Toni's Entfuehrung?
Er will immer noch Amara da rausholen und sich selbst als Tot ausgeben. Warum sollte er seine Tarnung hier riskieren?

Das haette alles auch per Anruf an Latif oder Abbas erfolgen koennen ohne zu enthuellen das Vince noch lebt.

Es folgt die Schiesserei mit den Chtulhus.

Ihr lasst Abbas durch Nebel zum haengenden Toni hinlaufen. Keiner der Rocker sieht was passiert.
Keiner der Hamadys sieht was passiert. Das ist eine Szene die zwischen Toni und Abbas ablaufen muesste.

Merke: Abbas der ueberhaupt nur da ist weil er dem Spitzel Vince geglaubt hat um seinem Bruder zu helfen.
Aus schlechtem Gewissen weil er selbst mit dem Deal mit der Polizei seinen Bruder hintergangen hat.
Mehr als er jemals seinem Bruder gegenueber Einsatz oder Vertrauen gezeigt hat.

Abbas haette zu Toni hinrennen sollen und vor ihm stehen bleiben, so wie vor hakeem.
Abbas realisiert hier dass der Mord an Ibrahim/Hakeem mit Toni verschwindet. Er besinnt sich auf seine Rolle als "Faust".
Dann gibt es einen Moment in dem Abbas Toni anstarrt und ueberlegt ob er das Geschaeft so an sich reissen kann indem er seinen Bruder toetet/verraet.

Kurz bevor er sich umdreht um zu gehen prescht auf einmal Vince durch den Rauch und klammert sich an Toni.
Vince ist mit dem Taxi aus eigenem Antrieb nicht zu Amara sondern zu dem Rockerheim gefahren um Toni zu retten.
Vince hebt Toni hoch und versucht ihm das Leben zu retten.

Abbas realisiert hier dass er seine Familie beschuetzen muss obwohl hier ein deutscher Bulle einen Anteil leistet egal wie viele Fehler er schon gemacht hat.

Zusammen befreien Sie Toni aus der Schlinge. Ruff schleicht sich an und rammt Vince das Messer in den Ruecken.

Kemal schiesst auf Ruff und verletzt ihn am Bauch.

Ruff geht zu Boden und Toni und Abbas verlassen die Lagerhalle.
Vince liegt mit einer tiefen Wunde in der Halle und starrt an die Decke.

Toni sagt zu Abbas er solle wegrennen (mit dem Wissen er wird wegen dem Polizistenmord in den Knast gehen).
Abbas rennt.

Toni geht zurueck in die Garage und haelt Vince waehrend er stirbt. Danach hebt er auf dem Weg nach draussen eine Pistole auf.
Er sieht wie Ruff (von Kemal getroffen) sich ueber den Boden schleppt.

Er schiesst Ruff durch den Kopf und beendet damit den aktuellen Krieg zwischen den Chtulhus und seiner eigenen Abneigung gegen das toeten.

== Die Ausstrahlung war anders

[Die Realitaet liegt beim Regisseur. Die Realitaet bzw. die Aussagen der jeweiligen Folter-Opfer unterscheidet sich. Das was "Nico" von sich gegeben hat ist zur haelfte dem Buegeleisen geschuldet. Am Ende verraet er das Versteck mit dem Koks. Das ist aber als eine der "Siege" in dieser Schlachtenserie zu sehen.]

-Nach der "Befreiung" im Clubhaus der Cthulhus-

Insert Shot drehen:
Toni sagt zu Abbas "Renn, Bruder, ich warte auf dich." (Mit allen Konsequenzen, Knast, Zeke packt aus, etc.)

Insert Shot drehen:
Vince flieht aus dem Auto nachdem die Hamady's das Tor der Chtulhus gerammt haben.

Insert Shot drehen:
Abbas sieht Toni in der Garage haengen waehrend die Rocker auf ihn schiessen, Flashback auf Onkel Hakeem der den Satz mit "Kopf und Faust" wiederholt. Abbas peilt Toni genauer an und rennt los.

Inser Shot drehen:
Toni kniet neben dem toten Vince und fluestert zu ihm. "Du warst mein Bruder, alhamdulillah. Ich kann dich jetzt nicht begraben, ich muss zu viele von meinen Bruedern begraben."

Toni steht auf und hebt eine silberne Pistole auf.

Er laeuft nach draussen, Kemal und die anderen schreien ihn an zum Auto zu laufen.

Er positioniert sich neben Ruff und starrt ihn an.

Ruff kriecht weiter am Boden entlang ohne zu reagieren.

Nahaufnahme auf Toni, Split-Shot mit der totalen.
Toni schiesst Ruf durch den Kopf.

Nahaufnahme Toni's verhaertetes, blutverschmiertes Gesicht. -> Staffel 2 Intro
