= Das Problem mit Deppen und Humor (German)
:author: Markus Napp
:email: mail@markus-napp.de
:toc-title: Inhalt
:icons: font
:revnumber: 1.0
:revdate: 09.10.2018
:stylesheet: ../boot-spacelab.css

== Deppen und Humor

Ich musste etwas mit meiner Aufmerksamkeitsschwaeche kaempfen um mich durch diesen tollen Artikel zu graben: link:https://uebermedien.de/32120/darueber-wird-man-doch-wohl-noch-nicht-lachen-duerfen/[Uebermedien: Darueber wird man doch wohl noch nicht lachen duerfen].

== Warum gut lachen wichtig ist

Comedy funktioniert durch Ueberraschung. Die klassische Setup/Punchline Kombination im Standup macht das sehr einfach deutlich. 
Es wird ein Spannungsbogen aufgebaut und dann meistens durch eine von der Erwartung abweichende Pointe wieder freigesetzt. 

Das Problem an der Art Humor eines Chris Nast oder Mario Barth ist dass die Fallhoehe der Spannung daraus besteht 
eine naive Erwartung aufzubauen. 

Redet er jetzt gleich schlecht ueber seine Freundin/werden sie dort wirklich ueber Vorteile abziehen und Menschen 
degradieren obwohl man das doch eigentlich nicht tun sollte? 

Ich weiss nicht einmal wie ich hoeflich Menschen umschreiben soll deren Horizont und Denkvermoegen aus so einer 
Perspektive noch etwas wie Ueberraschung empfinden.

Ich bin nur immer wieder sehr erschuettert darueber wie viele Menschen offenbar in so flachen geistigen Ebenen hausen. 
Ich selbst mag den erwaehnten Markus Barth (nicht Mario) allerdings als Konterprogramm sehr gerne. 
Sein Humor ist zwar sehr flach und extrem angestaubt sexistisch aber dabei ehrlich anspruchslos. Kein falsches Vertaeuschen von
Klasse oder Modernitaet. Flachwitze auf hohem Niveau. Kann man machen. Dass bei Humor Patterns aus dem 50/60er Jahren Frauen schlecht
davon kommen ist kaum zu vermeiden. Schade aber waere auch nicht authentisch wenn man es umzubauen versuchte.

Sonst bin ich eher so bei Serdar Somuncu, Moritz Neumeier, Hagen Rether zu Hause. 
In ihren Programmen halten die auf diversen Ebenen dem Publikum einen Spiegel vor. 
Anstatt kumpelhaft die Hand auf die Schulter zu legen um falsches Verhalten zu absolvieren wird dort bewusst 
(aber spielerisch) angeklagt und dem Zuhoerer selbst die Wahl seiner Vorwuerfe ueberlassen. 
Dort werden dann wirklich Tabus gebrochen und Dinge gesagt fuer die man sich nur im Kontext rechtfertigen kann.

Das Gegenteil dazu sind Menschen wie Chris Nast und viele andere, die immer wenn sie mal wieder auf der Suche nach Ruhm
etwas Dummes gesagt oder getan haben, so lange "Satire" schreien bis der Mob mit der Diskussion um die Definition 
des Begriffs endgueltig vom Thema abgelenkt hat. Echte Satire muss auch den Mut haben sich einem Shitstorm auszusetzen wenn,
Nein, gerade WEIL man ihn provoziert hat.

Satire zu schreien wenn man "schlechte Witze" meint ist wie mit einem Paddelboot auf der Wettkampfbahn herum zu fahren
nur weil man selbst Nichtschwimmer ist. Raus aus dem Becken!

Vielen Dank fuer diesen ausfuehrlichen und tollen Artikel!
