= V wie Vick dich Viral
:author: Markus Napp
:email: mail@markus-napp.de
:revnumber: 1.0
:revdate: 18/04/2016
:imagesdir: images
:toc-title: Inhalt
:icons: font
:stylesheet: ../boot-spacelab.css

Wie sich Künstler mit Fake Viral Clicks ergaunern.

== Heidi Joubert feat. KIDDO KAT

Ich bin mal `TOTAL` und vor allem `DAFÜR` in der S-Bahn irgend eine Unterhaltung zu bieten. Da kann es keinen Zweifel dran geben. Wenn ihr in der Bahn (gute) Musik spielt und den Leuten da eine Unterhaltung bietet bin ich der erst der applaudiert. Es muss halt gut sein.

NOTE: Es kommt vor allem darauf an zu welcher Uhrzeit und zu welchem Publikum ihr euer "Zeug" darbietet. Auf dem Weg zur Arbeit morgens früh gibt es von mir maximal einen neidischen, eher aber einen abwürdigenden Blick und ein "get a job"-Gefühl.

Spät Abends, nachdem man sich in das Fernverkehrssystem begeben hat um doch noch nach Hause zu finden, sind eure Darbietungen doch dann öfter schon eher gut gezielt. Um nicht zu sagen "toll". Und vor allem gerne genommen in der spartanischen Wüste der RMV-schen Unterhaltungswüste.

== Ach du Scheiße
Wenn es irgendwas gibt das mich mehr ankotzt als verhungernde Kinder in Afrika
oder ausgebeutete T-Shirt-Näher in der drei/einhalbten Welt dann ist es angebiedertes
"Viral"-Scheißentum das versucht mir irgend einen Mittelprächtigen Rotz mittels
Massenmedien als "Unique" und "total super guck das halt mal an du hipper Mensch"
zu verkaufen.

Heidi Joubert KIDDO KAT
Den "Ozzy Lino" kennt ihr bestimmt aucht sonst würdet ihr den "Hey das ist so random hier in der S-Bahn passiert"-Typ ja gar nicht kennent. Ach und Google hilft auch: https://www.facebook.com/ozzylino / http://jewlsverse.com/web/biography/ (im Geschäft seit 1992) ... woah SPONTAN!!!1!

Sogar die selbe Jacke hat der Security an.

=== Die Bahn
Der ganze Scheiß findet statt in der S5 zwischen Frankfurt Süd und Bad Homburg/Friedrichsdorf

== Links
All of these videos have been recorded withing about a week or so on the *S5" line of the RMV trains.
From most of the videos you can tell that the train is travelling towards "Friedrichsdorf Bahnhof" (which is not exactly a desirable destination.)

So we have these videos

[options="header", cols="3"]
|===
|Upload Date
|URL
|Timetamp (Minutes)

|15.04.2016
|https://youtu.be/XF6shrBX4L8?t=128
|`2:08` with the brown pants

|18.04.2016
|https://youtu.be/O1eDQmSNkCw?t=11
|`0:12` left of the drummer_ess

|18.04.2016
|https://youtu.be/2iOsUbBJ4nQ?t=139
|`2:19` Security Dude (brown pants again, upper left hand corner)
Ozzy Lino doing the "improvised" singing part

|24.04.2016
|https://youtu.be/6YPhr4i-hwE?t=13
|`0:13` Security Dude again (standing next to the window):
|===

=== Die Faker

==== KIDDO KAT
* http://kiddo-kat.de/
* https://www.facebook.com/kiddokatmusic/

==== Ozzy Lino
* https://www.youtube.com/watch?v=6YPhr4i-hwE
* https://www.facebook.com/ozzylino

==== Heidi Joubert
* https://www.facebook.com/heidi.joubert
* https://www.youtube.com/user/cajonschool
* https://www.facebook.com/heidijoubertcajon/

=== Video

Ich fahre die Linie jeden Tag. Das ist eine der ruhigsten (in Sachen Krawall) im ganzen Gebiet gerade in der Richtung und um die Uhrzeit.

Rödelheim - S5 Friedrichsdorf (visible at https://youtu.be/2iOsUbBJ4nQ?t=131 (shaky))
https://www.youtube.com/watch?v=2iOsUbBJ4nQ

KIDDO
Leider muss ich bei jedem deiner Videos beinahe reflexartig vor dem Kotzen zurückweichen. Beliebiger geht es eigentlich (auch mit viel Anstrengung) nicht.
