= Claas Relotius beschwert sich über Enthüllungen
:author: Markus Napp
:email: mail@markus-napp.de
:imagesdir: images
:toc-title: Inhalt
:icons: font
:revnumber: 1.1
:revdate: 23.10.2019
:stylesheet: ../boot-spacelab.css
:claas: Claas Relotius

Der als Lügner überführte und hoffentlich mittlerweile verstoßene Lügner {claas} wehrt sich
gegen seinen Ex-Kollegen Juan Moreno. Dieser hatte in einem Buch die Vorgänge des Betruges beschrieben mit denen sich {claas} in der Redaktion des SPIEGELs nahezu uneingeschränkten Einfluss verschaffen konnte. An welchem zu hustenden Privileg dass nun gelegen haben mag können wir gerne an andere Stelle diskutieren.

In der, für Geld, an die ZEIT verkauften Kritik behauptet Lügen-Claas zum Beispiel diverse Dinge die man dank Paywall nicht einfach nachvollziehen kann und mit größter Wahrscheinlichkeit auch noch ein Honorar für Lügen-Claas generieren.

In einem Artikel des link:https://uebermedien.de/42567/juan-moreno-und-der-fluch-der-fast-perfekten-pointe/["ÜberMedien"-blog] wird der Artikel wie folgt zitiert:

"Die Substanz von Morenos Buch greift Relotius nicht an. Trotzdem geht es um mehr als Lappalien."

Aus irgend einem Grund verschreibt sich hier der Autor Niggemeier in den Satz:
"Es geht um Morenos Glaubwürdigkeit als Reporter und als Kritiker von Relotius." als ob die Glaubwürdigkeit einer Person damit in Frage gestellt würde dass von ihr kritisierte Personen diese wiederum in Frage stellten.

Wenn dich jemand als Lügner bezeichnet bist du einfach erstmal ein Lügner dann kommt erstmal der Nachweis. Sollte man die Lüge dann auch noch `59` mal nachweisen ... kurze Pause für den Facepalm ... sollte sich der Lügner dann eigentlich vor allem erstmal in Schweigen hüllen und hoffen dass auch nicht der letzte Fastfood-Ketten-Manager in der Umgebung von seiner Beziehung
zur Realität erfährt.

Entgegen Moreno hat Relotius einen `59:0` Rückstand. Selbst wenn man Moreno alle seiner immerhin angeblich `22` angeprangerten Behauptungen als Erfindung oder Manipulation nachweisen würde (wohlgemerkt in einer einzigen Geschichte) wäre das immerhin noch ein weiter Vorsprung von `37` als _komplett_ nachgewiesenen Lügen. Ich glaube für die Auflistung aller Einzelfalschbehauptungen in den `59` Geschichten hätte selbt der schlimmste Relotius-Apologet nicht genug Lebenszeit zur Verfügung oder käme vorher zur Besinnung. Selbst einem Donald Trump würde es schwer fallen diese Dimensionen zu überspielen.

Doch zurück zur Logik des Lügen-Claas zur Wertigkeit des Kommentators. Nach seiner Logik wäre Stefan Niggemeier längst nicht mehr Blog-Author oder gefragter Medienkommentator sondern nicht einmal mehr Hundesitter bei Sarah Kuttner. Falschbehauptungen (unbewiesen oder nicht) und nachvollzogene und unwiderlegte Lügen sind nun einfach mal das selbe. Dass Lügen-Claas nahezu seine komplette Arbeit für den SPIEGEL erfunden hat, dass er an keiner Stelle eine Aufklärung unterstützt oder gar begleitet hat ist für ihn irrelevant. Aufklärung ist etwas für Perückenträger aus dem 16. Jahrhundert. Lesen Sie im folgend Artikel was Voltaire zur AfD gesagt hat. Exklusiv beim SPIEGEL, Autor Claas Relotius.

So funktioniert ein SinterClaas-Relotius. Geschichte hat nen Bart und wird von allem außer den Kindern als merkwürdig empfunden und doch aus kommerzgründen überall zelebriert.
Hohoho - Ho - No!

Ich stelle hier mal eine Gegenverschwörung auf:

Sorry, aber ist das Buch nicht auch einfach ein Beweis und eine Weiterführung dieser Anklage? Da betrügt ein bekannter und beliebter Journalist eines der größten Magazine Deutschlands, alle sind zu involviert oder feige um etwas zu sagen und er kommt ungeprüft davon.

Und dann: Einer der Kollegen der ihm das vorwirft weisst ihm diese Täuschung dann auch noch auf weitestgehend eigenes Risiko und eigene Rechnung nach. Dann erst wird der skeptische Kollege auffälligerweise von seiner Redaktion "begnadigt" und Deutschland schießt sich auf den Spitzenenthüller ein. Nicht aber ohne zuvor Entlassungs- und Mobbingdrohungen zu erhalten.

Dann veröffentlicht der "Enthüller" ein Buch in dem Teile -angeblich (lt. dem überführten Lügner)- nicht stimmen und es wird dennoch (jetzt mal ganz genau aufpassen) von allen Lektoren, dem Verlag, den beteiligten Kollegen und Freunden nahezu ungeprüft durchgewunken weil man den "Erfolg" wittert? Also hat die SPIEGEL Redaktion, die man gerade so massiv betrogen hat einem mindestens mals in Abhängigkeit stehenden Journalisten die Veröffentlichung eines Manuskripts gestattet dass weitere (für das Magazin schädliche) Behauptungen enthält? Dass dabei die Realität (in diesem Fall das Wirken der Person Relotius) zu kurz kommt hat niemanden interessiert? Oder ist sie gar nicht zu kurz gekommen? Das klingt alles entweder nach großem Versagen, massiver Verschwörung oder unbeschränkter Inkompetenz.

Keines der Szenarien ist für die Leser zuträglich. Moreno enthüllt mit dem Buch die eigene (nachvollziehbare) Kapitalisierung der Enthüllung. Relotius gibt sich weiter seinem Ego hin der
auch in der schmetternden Niederlage noch feinsten Unsinn zu seinen Gunsten ausgelegt hören will.
Die ZEIT verspricht sich offenbar die Gegenempörung der Claas-Apologeten zu ihren Gunsten zu nutzen. Wer an den Lügen anderer verdient muss sich hoffentlich zukünftig selbst mehr Fragen gefallen lassen.

Wo, Bitte ist dieses Buch, -gelogen oder nicht- NICHT eine Fortführung der Enthüllung? Wieso sollte jemand der Lügner entlarven will, lügen in einem Rahmen in dem jede Lüge auffliegen "müsste" wenn es denn um "Lügen" ginge. Aber geht es ja nicht. Es geht um Umsatz, Absatz, Click-Zahlen, Aufmerksamkeit.

Scheißegal ob es stimmt, wenn man nach dem Prozess in X Monaten eine Gegendarstellung irgendwo verstecken muss. Das Geld ist bis dahin ausgegeben.

Wenn jemand sich riskiert um DIE DA aufzudecken, warum sollte er dann VOR UNS Respekt haben? Ob das Buch wahrheitsgemäß ist oder nicht spielt ab diesem Zeitpunkt in unserer Diskurs-Gesellschaft keine Rolle mehr. Schwarz oder Moreno. Claas oder Weiss. Who gives a fuck?

Wer hier auf jeden Fall profitiert sind Relotius weil sein Name weiter in den Medien bleibt mit dem Beigeschmack der Verschwörten Diskreditierung. Es profitiert Moreno weil sein Name der allenfalls Stammlesern und Industrievertrauten ein Begriff gewesen sein mag jetzt bei Menschen wie mir im Gedächtnis verankert sind. Es profitieren Suhrkamp und Rowohlt weil sowohl die vorherigen Werde des Claas als auch die Aufklärung jetzt zu Studienzwecken gekauft werden. Es profitieren außerdem der SPIEGEL der nun kritisch beäugt wird ob jeden Artikels. Es profitieren ZEIT und alle anderen Medien die Aufklärer Moreno als auch Angeklagten Relotius haben zu Wort kommen lassen. Es profitieren Fernseh- und Radiosender die mit Debatten über das Thema Sendezeit füllen und alle Betreiber von Internetplatformen auf denen mindestens einer der genannten Namen oder Marken in den Empfehlungsalhorithmen gelandet sind.

Der einzige Verlierer ist wie immer der Leser. Kein Verlag, kein Autor, kein Sender und keine Diskussionsgruppe widmet sich dem Thema wie man denn in einer von solchem Scheißdreck geprägten Welt noch ehrlich Arbeit erkennen und zur Meinungsbildung nutzen können soll. Keine Maischberger oder Plaßberg-Sendungen zu dem Thema "Ihr wollt uns alle verarschen, was nun?".

Sofern man sich die Historie der Medien in Sachen "Wahrheit" in den letzten Jahrzehnten anschaut sollte Überraschung zum Fall Relotius die letzte Emotion sein. Am ehesten noch bleibt die konfuse Fragestellung: "Warum funktioniert das eigentlich seit je her und immer noch?".

Der Gegenbeweis dass es nicht so ist muss erstmal glaubhaft angetreten werden. Ich bin gespannt.
