= Claas Relotius beschwert sich über Enthüllungen
:author: Markus Napp
:email: mail@markus-napp.de
:imagesdir: images
:toc-title: Inhalt
:icons: font
:revnumber: 1.0
:revdate: 23.10.2019
:stylesheet: ../boot-spacelab.css
:claas: Claas Relotius

Der als Lügner überführte und hoffentlich mittlerweile verstoßene Lügner {claas} wehrt sich
gegen seinen Ex-Kollegen Juan Moreno. Dieser hatte in einem Buch die Vorgänge des Betruges beschrieben mit denen sich {claas} in der Redaktion des Spiegels nahezu uneingeschränkten Einfluss verschaffen konnte. An welchem zu hustenden Privileg dass nun gelegen haben mag können wir gerne an andere Stelle diskutieren.

In der, für Geld, an die ZEIT verkauften Kritik behauptet Lügen-Claas zum Beispiel diverse Dinge die man dank Paywall nicht einfach nachvollziehen kann und mit größter Wahrscheinlichkeit auch noch ein Honorar für Lügen-Claas generieren.

In einem Artikel des link:https://uebermedien.de/42567/juan-moreno-und-der-fluch-der-fast-perfekten-pointe/["ÜberMedien"-blogs] wird der Artikel wie folgt zitiert:
"Die Substanz von Morenos Buch greift Relotius nicht an. Trotzdem geht es um mehr als Lappalien."

Aus irgend einem Grund verschreibt sich hier der Autor Niggemeier in den Satz:
"Es geht um Morenos Glaubwürdigkeit als Reporter und als Kritiker von Relotius." als ob die Glaubwürdigkeit einer Person damit in Frage gestellt würde dass von ihr kritisierte Personen diese wiederum in Frage stellten. Wenn dich jemand als Lügner bezeichnet bist du einfach erstmal ein Lügner, sollte man dir das dann auch `59` mal nachgewiesen werden ... kurze Pause für den Facepalm ... sollte sich der Lügner dann eigentlich vor allem erstmal in Schweigen hüllen und hoffen dass auch nicht der letzte Fastfood-Ketten-Manager in der Umgebung von seiner Beziehung
zur Realität erfährt.

Entgegen Moreno hat Relotius einen 59:0 Rückstand. Auch wenn man Moreno alle seiner 22 angeprangerten Behauptungen als Erfindung oder Manipulation nachweisen würde wäre das immerhin noch ein weiter Vorsprung von 37 Lügen. Selbst einem Donald Trump würde es schwer fallen diese
Dimensionen zu überspielen.

Doch zurück zur Logik des Lügen-Claas zur Wertigkeit des Kommentators. Nach seiner Logik wäre Stefan Niggemeier längst nicht mehr Blog-Author oder gefragter Medienkommentator sondern nicht einmal mehr Hundesitter bei Sarah Kuttner. Falschbehauptungen (unbewiesen oder nicht) und nachvollzogene und unwiderlegte Lügen sind nun einfach mal das selbe. So funktioniert ein SinterClaas-Relotius. Geschichte hat nen Bart und wird von allem außer den Kindern als merkwürdig empfunden und doch aus Kommerzgründen überall zelebriert. Hohoho - Ho - No!

Sorry aber ist das Buch nicht auch einfach ein Beweis und eine Weiterführung dieser Anklage? Da betrügt ein bekannter und beliebter Journalist eines der größten Magazine des Landes und kommt ungeprüft davon. Einer der Kollegen der ihm das vorwirft weisst ihm diese Täuschung dann auch noch auf weitestgehend eigenes Risiko und eigene Rechnug nach. Dann erst wird der skeptische Kollege auffälligerweise von seiner Redaktion "begnadigt" und Deutschland schießt sich auf den Spitzenenthüller ein. Nicht aber ohne zuvor Entlassungs- und Mobbingdrohungen zu erhalten. Dann veröffentlicht der "Enthüller" ein Buch in dem Teile -angeblich (lt. dem überführten Lügner) nicht stimmen und es wird dennoch (jetzt mal ganz genau aufpassen) von allen Lektoren, dem Verlag, den beteiligten Kollegen und Freunden nahezu ungeprüft durchgewunken weil man den "Erfolg" wittert. Dass dabei die Realität (in diesem Fall das Wirken der Person Relotius) zu kurz kommt hat niemanden interessiert? Oder ist sie gar nicht zu kurz gekommen?

Wo, Bitte, ist das nicht eine Fortführung der Enthüllung? Wieso sollte jemand der Lügner entlarven will lügen in einem Rahmen in dem jede Lüge auffliegen "müsste" wenn es denn um "Lügen" ginge. Aber geht es ja nicht. Es geht um Umsatz, Absatz, Click-Zahlen, Aufmerksamkeit.

Scheißegal ob es stimmt, wenn man nach dem Prozess in X Monaten eine Gegendarstellung irgendwo verstecken muss. Das Geld ist bis dahin ausgegeben.

Wenn jemand sich riskiert um DIE DA aufzudecken, warum sollte er dann VOR UNS Respekt haben? Ob das Buch wahrheitsgemäß ist oder nicht spielt ab diesem Zeitpunkt in unserer Diskurs-Gesellschaft keine Rolle mehr. Schwarz oder Moreno. Claas oder Weiss. Who gives a fuck?

Geld ist Nummer eins und tröpfelt eben nach unten, Bullshit wird halt groß gemacht.
